openapi: 3.0.0
info:
  title: cb-driver-api
  version: 1.0.0
servers:
  - url: http://localhost:8080
  - url: http://{{base_url}}
  - url: http://{{dev_url}}
  - url: https://cb-client-location-updates-api-ukxjb66ceq-ew.a.run.app
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
paths:
  /pooling/simulate/fcm:
    post:
      tags:
        - default
      summary: simulate new app fcm
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: YmuHJz2QrNqwznyG1Y9D
                trip_id: trip_id
                push_token: >-
                  dpqNszaFQDa2I0I_JqZBxy:APA91bFGdQD0WGUZNO-n0IsCegasWcZYk1o5kpnHMHcB-gRdFtWfziy9POkLaUyNY9pFTeXa_Hkvqzaw4tFxh57yBONLxD7uXOW6zcjVCx47olz5G-iXrG8ixFJfw4R7Du8itvqQMeVv
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /driver/update/push-token:
    post:
      tags:
        - default
      summary: updates driver's push token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                push_token: >-
                  c9whx29ZQaG4JjU2RGVCG2:APA91bFYfwb8wCBWWLfd0pFirlQnbZrqE2SB-yyMlV64fWsTXQo9dwEQvNJ0ONN1Iu277f9oOLrYqoMDm7OC6thijiTV2gf0EWg5yAU_pdn0-niZUlzOHL8mmcqMbZTiDXepJwsBIFwZ
                location:
                  latitude: -26.042088
                  longitude: 28.016763
                  accuracy: 20.9
                  altitude: 78
                  speed: 0.19733982
                  speedAccuracy: 0
                  provider: fused
                  bearing: 237.07773
                  bearingAccuracy: 0
                  verticalAccuracy: 1.3333334
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /driver/send/sos:
    post:
      tags:
        - default
      summary: send SOS
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                location:
                  latitude: -26.042088
                  longitude: 28.016763
                  accuracy: 20.9
                  altitude: 78
                  speed: 0.19733982
                  speedAccuracy: 0
                  provider: fused
                  bearing: 237.07773
                  bearingAccuracy: 0
                  verticalAccuracy: 1.3333334
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /driver/me:
    get:
      tags:
        - default
      summary: me - get logged in driver
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /driver/start-lunch:
    post:
      tags:
        - default
      summary: start lunch
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                location:
                  latitude: -26.042088
                  longitude: 28.016763
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /driver/end-lunch:
    post:
      tags:
        - default
      summary: end lunch
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /driver/go-online:
    post:
      tags:
        - default
      summary: go online
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                push_token: >-
                  eVuQ67niR1SLodfZ6P14mS:APA91bGl_hYzMj_PXT_uhR0GY9iJEP0iFj-i2hw_UcMIk5WayGlTCM2CadQFk9Pe-eZyLpcy0gwsJZJBeksqmY7nikPN5vXgbqCO8SyYn3kjv7AhggZsPFQjpSq7z2fKWgnanKWCftSI
                location:
                  latitude: -26.042088
                  longitude: 28.016763
                  accuracy: 20.9
                  altitude: 78
                  speed: 0.19733982
                  speedAccuracy: 0
                  provider: fused
                  bearing: 237.07773
                  bearingAccuracy: 0
                  verticalAccuracy: 1.3333334
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /driver/go-offline:
    post:
      tags:
        - default
      summary: go offline
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                location:
                  latitude: -26.042088
                  longitude: 28.016763
                  accuracy: 20.9
                  altitude: 78
                  speed: 0.19733982
                  speedAccuracy: 0
                  provider: fused
                  bearing: 237.07773
                  bearingAccuracy: 0
                  verticalAccuracy: 1.3333334
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /driver/notify-fcm:
    post:
      tags:
        - default
      summary: simulate push notification - (deprecated)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                push_token: >-
                  cF9fXx7rRmqe0XlPk25BrV:APA91bFWMGZOIOs4mmPMgpwlI8H0m-IkiE8P_WsEbvl8oNI2rBh2Dp9ScpSp7GRW-ZnzVA0byEoUUhE4amtkmzWdQHiledqrCy0fZpnKLXEmn_SiU4JGukNOBh_nd3qXhcY94dOgFFVo
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /trip/ckw3pYRwD8FJNznzyU2r/client/6IB4FgVQZyQIG9T2xdEx:
    get:
      tags:
        - default
      summary: get trip
      description: https://{url}/trip/{trip_id}/client/{client_id}
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /trip/ke3QmxMCSosaFRX8ga31/client/YmuHJz2QrNqwznyG1Y9D:
    get:
      tags:
        - default
      summary: check wallet
      description: https://{url}/trip/{trip_id}/client/{client_id}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /trip/accept:
    post:
      tags:
        - default
      summary: accept trip
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: pGZ4tqSopwEcMK59MS96
                trip_id: Sd9Sf5LsGaGh9csjLHqW
                location:
                  latitude: 0
                  longitude: 0
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /trip/acceptAdhoc:
    post:
      tags:
        - default
      summary: accept adhoc 2
      description: >-
        This endpoint creates a trip, it takes in the branch_id, order_ids,
        vehicle_type, TSP in the body
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: zG8d6LmGTMH09W63O2U3
                trip_id: Oba7Zx1cHCrLw3Se6T8k
                order_id: v28ocU1EISQTclMTabPU
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /trip/reject:
    post:
      tags:
        - default
      summary: reject trip
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: YmuHJz2QrNqwznyG1Y9D
                trip_id: vFLJpx0OhZFxFLMHx9xv
                location:
                  latitude: -26.042088
                  longitude: 28.016763
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /trip/received/notification:
    post:
      tags:
        - default
      summary: trip notification received
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: YmuHJz2QrNqwznyG1Y9D
                trip_id: l6SKjCAeVnhxxdyM99lG
                location:
                  latitude: -26.042088
                  longitude: 28.016763
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /trip/rollback:
    post:
      tags:
        - default
      summary: rollback trip - (deprecated)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: UItXbYwpy9a6vf9e5aKf
                trip_id: JaRfoPU5Z7sdsStmLBzC
                location:
                  latitude: -26.042088
                  longitude: 28.016763
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /trip/arrived/collection-point:
    post:
      tags:
        - default
      summary: arrived at branch/collection point
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: YmuHJz2QrNqwznyG1Y9D
                trip_id: l6SKjCAeVnhxxdyM99lG
                location:
                  latitude: -26.042088
                  longitude: 28.016763
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /trip/start:
    post:
      tags:
        - default
      summary: start trip
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: YmuHJz2QrNqwznyG1Y9D
                trip_id: l6SKjCAeVnhxxdyM99lG
                location:
                  latitude: -26.042088
                  longitude: 28.016763
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /order/collect:
    post:
      tags:
        - default
      summary: collect order
      description: |-
        # Updating order assignable

        Lorem lorem
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: YmuHJz2QrNqwznyG1Y9D
                trip_id: l6SKjCAeVnhxxdyM99lG
                order_id: 241iDdzVRZbgAF1OZYzf
                location:
                  latitude: -26.042088
                  longitude: 28.016763
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /order/collect-with-parcels:
    post:
      tags:
        - default
      summary: collect order with parcels
      description: |-
        # Updating order assignable

        Lorem lorem
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: YmuHJz2QrNqwznyG1Y9D
                trip_id: 51iBQ098PxAN87nsqPCK
                order_id: AehA0YPi6nQc0WoWuWWS
                parcel_qr_codes:
                  - ESTIMATE1
                location:
                  latitude: -26.042088
                  longitude: 28.016763
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /order/in-transit:
    post:
      tags:
        - default
      summary: in transit (driver departed)
      description: |-
        # Updating order assignable

        Lorem lorem
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: YmuHJz2QrNqwznyG1Y9D
                trip_id: l6SKjCAeVnhxxdyM99lG
                order_id: 241iDdzVRZbgAF1OZYzf
                location:
                  latitude: -26.042088
                  longitude: 28.016763
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /order/arrived-at-customer:
    post:
      tags:
        - default
      summary: arrived at customer
      description: |-
        # Updating order assignable

        Lorem lorem
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: YmuHJz2QrNqwznyG1Y9D
                trip_id: l6SKjCAeVnhxxdyM99lG
                order_id: 241iDdzVRZbgAF1OZYzf
                location:
                  latitude: -26.042088
                  longitude: 28.016763
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /order/abandon:
    post:
      tags:
        - default
      summary: new abandon order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: YmuHJz2QrNqwznyG1Y9D
                trip_id: 51iBQ098PxAN87nsqPCK
                order_id: AehA0YPi6nQc0WoWuWWS
                reason: ''
                location:
                  latitude: -26.042088
                  longitude: 28.016763
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /order/deliver:
    post:
      tags:
        - default
      summary: deliver order
      description: |-
        # Updating order assignable

        Lorem lorem
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: RlOno84MTS2YNZMQDMe3
                trip_id: yhshTFhNf4qC1f0CLD0a
                order_id: L8D9wUgGWk01pFucTIlC
                location:
                  latitude: -25.7480574
                  longitude: 28.1857857
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /trip/abandon-order:
    post:
      tags:
        - default
      summary: abandon order (deprecated)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: YmuHJz2QrNqwznyG1Y9D
                trip_id: 51iBQ098PxAN87nsqPCK
                order_id: AehA0YPi6nQc0WoWuWWS
                reason: ''
                location:
                  latitude: -26.042088
                  longitude: 28.016763
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /order/sign/pod:
    post:
      tags:
        - default
      summary: signed POD after delivery -  (deprecated)
      description: |-
        # Updating order assignable

        Lorem lorem
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: UItXbYwpy9a6vf9e5aKf
                order_id: J6P4v6qoE9vDceyPgblN
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /trip/end:
    post:
      tags:
        - default
      summary: end trip
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: YmuHJz2QrNqwznyG1Y9D
                trip_id: l6SKjCAeVnhxxdyM99lG
                location:
                  latitude: -26.042088
                  longitude: 28.016763
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /driver/activity:
    post:
      tags:
        - default
      summary: driver event webhook
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                driver_id: lGLlL6WiHqTBFByph5EU
                event: driver.online
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /order/return:
    post:
      tags:
        - default
      summary: return order
      description: |-
        # Updating order assignable

        Lorem lorem
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: ayce3l5n0QSA7FO7CDtr
                trip_id: jJ4aSfwlQU0klCsvbidF
                order_id: dO8czrVPbdCm1asgYiH3
                location:
                  latitude: -26.042088
                  longitude: 28.016763
                optional_settings:
                  otp: '0000'
                  qr_codes:
                    - '10111'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /trip/HiH83P7y3iDGjtNO5MUj/client/YmuHJz2QrNqwznyG1Y9D:
    get:
      tags:
        - default
      summary: get trip Copy 2
      description: https://{url}/trip/{trip_id}/client/{client_id}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /trip/rejectAdhoc:
    post:
      tags:
        - default
      summary: reject adhoc order
      description: >-
        This endpoint creates a trip, it takes in the branch_id, order_ids,
        vehicle_type, TSP in the body
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: zG8d6LmGTMH09W63O2U3
                trip_id: tWAj8jTmhoTq3u3dVmie
                order_id: 7InVNEXMuZYBbniZNYQC
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /order/update/parcels:
    post:
      tags:
        - default
      summary: update parcels
      description: |-
        # Updating order assignable

        Lorem lorem
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: |-
                {
                    "client_id": "ayce3l5n0QSA7FO7CDtr",
                    "order_id": "sZDLUhr3JKDsb84SfOK1",
                    "parcels": [
                {
                        "qr_code": "ESTIMATE25",
                        "size": "Small",
                        "quantity": 3
                    },
                    {
                        "qr_code": "ESTIMATE25",
                        "size": "Large",
                        "quantity": 4
                    },
                    {
                        "qr_code": "ESTIMATE25",
                        "size": "Medium",
                        "quantity": 6
                    }
                    ]
                }

                {{
                        "qr_code": "ESTIMATE25",
                        "size": "Small",
                        "quantity": 3
                    },
                    {
                        "qr_code": "ESTIMATE25",
                        "size": "Large",
                        "quantity": 4
                    },
                    {
                        "qr_code": "ESTIMATE25",
                        "size": "Medium",
                        "quantity": 6
                    }}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /order/update/payment-fields:
    post:
      tags:
        - default
      summary: update order payment fields
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: ayce3l5n0QSA7FO7CDtr
                order_id: rEdC7XKcpUIMqpGxzCtd
                trip_id: TcgIGHRAacCPD1tVfQdw
                payment_type: cash
                delivery_price: 25.7
                post_payment_flow:
                  type: cash_pin_required
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /order/payment/verify-pin:
    post:
      tags:
        - default
      summary: verify order cash pin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                client_id: ayce3l5n0QSA7FO7CDtr
                order_id: sZDLUhr3JKDsb84SfOK1
                trip_id: sZDLUhr3JKDsb84SfOK1
                cash_pin: 1234
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
